package agents

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/odin-ai/odin/pkg/logger"
)

// ClaudeInstaller installs Claude Code configuration
type ClaudeInstaller struct{}

// ID returns the agent ID
func (c *ClaudeInstaller) ID() AgentID {
	return "claude-code"
}

// Name returns the agent name
func (c *ClaudeInstaller) Name() string {
	return "Claude Code"
}

// Available checks if Claude Code CLI is installed
func (c *ClaudeInstaller) Available() bool {
	return DetectCLI("claude")
}

// claudeMdTemplate is the CLAUDE.md template for Claude Code
const claudeMdTemplate = `# Claude Code - ODIN Managed Configuration

## Project Overview
This is an ODIN-managed Claude Code configuration.

## Model Configuration
{{if .Model}}Model: {{.Model}}{{else}}Using default model{{end}}

## Project Rules

### General Guidelines
- Follow the ODIN SDD workflow for all changes
- Use local-first, offline-capable tools when possible
- Respect the project's existing architecture

### SDD Workflow
1. Explore: Investigate ideas before committing
2. Propose: Create change proposals
3. Spec: Write specifications with requirements
4. Design: Document technical architecture
5. Tasks: Break down into implementation tasks
6. Apply: Implement code following specs
7. Verify: Validate implementation matches specs
8. Archive: Sync and archive completed changes

### Code Style
- Format: gofmt + goimports
- Lint: golangci-lint
- Tests: go test -race -cover

## Integration
This configuration is managed by ODIN AI.
Do not edit manually - changes will be overwritten.
`

// agentsMdTemplate is the AGENTS.md template
const agentsMdTemplate = `# Agents Configuration

This directory contains agent-specific configurations managed by ODIN.

## Structure
- CLAUDE.md: Claude Code configuration
- Rules are stored in the rules/ subdirectory

## Updates
This configuration is auto-generated by ODIN's agents module.
`

// Install installs the Claude Code configuration
func (c *ClaudeInstaller) Install(cfg *AgentConfig) error {
	homeDir, _ := os.UserHomeDir()
	basePath := filepath.Join(homeDir, ".claude")
	rulesPath := filepath.Join(basePath, "rules")

	// Create directories
	if err := os.MkdirAll(rulesPath, 0755); err != nil {
		return fmt.Errorf("failed to create claude directory: %w", err)
	}

	// Generate CLAUDE.md
	tmpl, err := template.New("claudeMd").Parse(claudeMdTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	claudeMdPath := filepath.Join(basePath, "CLAUDE.md")
	f, err := os.Create(claudeMdPath)
	if err != nil {
		return fmt.Errorf("failed to create CLAUDE.md: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, cfg); err != nil {
		return fmt.Errorf("failed to write CLAUDE.md: %w", err)
	}

	// Generate AGENTS.md in rules directory
	agentsMdPath := filepath.Join(rulesPath, "AGENTS.md")
	f2, err := os.Create(agentsMdPath)
	if err != nil {
		return fmt.Errorf("failed to create AGENTS.md: %w", err)
	}
	defer f2.Close()

	if _, err := f2.WriteString(agentsMdTemplate); err != nil {
		return fmt.Errorf("failed to write AGENTS.md: %w", err)
	}

	logger.Info("Claude Code configuration installed", "path", basePath)
	return nil
}

// Verify checks if Claude Code configuration is properly installed
func (c *ClaudeInstaller) Verify() error {
	homeDir, _ := os.UserHomeDir()
	claudeMdPath := filepath.Join(homeDir, ".claude", "CLAUDE.md")

	if _, err := os.Stat(claudeMdPath); os.IsNotExist(err) {
		return fmt.Errorf("CLAUDE.md not found at %s", claudeMdPath)
	}

	return nil
}

// Uninstall removes the Claude Code configuration
func (c *ClaudeInstaller) Uninstall() error {
	homeDir, _ := os.UserHomeDir()
	claudePath := filepath.Join(homeDir, ".claude")

	if err := os.RemoveAll(claudePath); err != nil {
		return fmt.Errorf("failed to remove claude directory: %w", err)
	}

	logger.Info("Claude Code configuration uninstalled")
	return nil
}
