// Package deploy provides the Dvergar forge/deploy system for ODIN
package deploy

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// GenerateInstallScript generates the installation script
func GenerateInstallScript(info *SystemInfo, cfg *DeployConfig) (string, error) {
	tmpl := `#!/usr/bin/env bash
# ODIN AI Installation Script
# Generated by Dvergar - The Norse Forge/Deploy System

set -euo pipefail

# Configuration
INSTALL_PATH="{{.InstallPath}}"
BACKUP_PATH="{{.BackupPath}}"
LOG_PATH="{{.LogPath}}"
COSIGN_KEY="{{.CosignKey}}"
VERSION="{{.Version}}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging
log() {
    echo -e "${GREEN}[ODIN]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[ODIN WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ODIN ERROR]${NC} $1" >&2
}

# Detect OS and Architecture
detect_os() {
    case "$(uname -s)" in
        Linux*)     echo "linux" ;;
        Darwin*)    echo "darwin" ;;
        CYGWIN*)    echo "windows" ;;
        MINGW*)     echo "windows" ;;
        *)          echo "unknown" ;;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        x86_64)     echo "amd64" ;;
        aarch64)    echo "arm64" ;;
        arm64)      echo "arm64" ;;
        amd64)      echo "amd64" ;;
        *)          echo "unknown" ;;
    esac
}

# Detect if running in container
detect_container() {
    if [ -f "/.dockerenv" ]; then
        echo "docker"
    elif [ -f "/run/.containerenv" ]; then
        echo "podman"
    elif [ -d "/var/run/secrets/kubernetes.io" ]; then
        echo "kubernetes"
    else
        echo ""
    fi
}

# Verify cosign signature
verify_cosign() {
    log "Verifying binary signature with cosign..."
    
    if ! command -v cosign &> /dev/null; then
        warn "cosign not found, skipping verification"
        return 0
    fi
    
    if [ -z "$COSIGN_KEY" ]; then
        warn "COSIGN_KEY not set, skipping verification"
        return 0
    fi
    
    # Download signature and certificate
    SIGNATURE_URL="${COSIGN_KEY}.sig"
    CERT_URL="${COSIGN_KEY}.crt"
    
    echo "$SIGNATURE_URL" | cosign verify --signature @- \
        --certificate ${CERT_URL} \
        "${INSTALL_URL}" 2>/dev/null || {
        error "cosign verification failed!"
        return 1
    }
    
    log "Binary verified successfully"
    return 0
}

# Create backup of existing installation
backup_existing() {
    if [ -f "$INSTALL_PATH" ]; then
        log "Backing up existing installation..."
        
        mkdir -p "$BACKUP_PATH"
        
        BACKUP_FILE="$BACKUP_PATH/odin-backup-$(date +%Y%m%d-%H%M%S)"
        cp "$INSTALL_PATH" "$BACKUP_FILE"
        
        log "Backup created at $BACKUP_FILE"
        
        # Store rollback script
        cat > "$BACKUP_PATH/rollback.sh" << 'ROLLBACK_EOF'
#!/usr/bin/env bash
# Rollback script - restores from latest backup
set -e
BACKUP_DIR="{{.BackupPath}}"
INSTALL_PATH="{{.InstallPath}}"

LATEST=$(ls -t "$BACKUP_DIR"/odin-backup-* 2>/dev/null | head -1)
if [ -z "$LATEST" ]; then
    echo "No backup found"
    exit 1
fi

echo "Rolling back to: $LATEST"
cp "$LATEST" "$INSTALL_PATH"
chmod +x "$INSTALL_PATH"
echo "Rollback complete"
ROLLBACK_EOF
        chmod +x "$BACKUP_PATH/rollback.sh"
    fi
}

# Download and install binary
download_and_install() {
    log "Downloading ODIN AI..."
    
    OS=$(detect_os)
    ARCH=$(detect_arch)
    CONTAINER=$(detect_container)
    
    # Determine download URL based on detected OS/arch
    DOWNLOAD_BASE="${DOWNLOAD_URL:-https://get.odin.ai/releases}"
    BINARY_NAME="odin-${OS}-${ARCH}"
    if [ "$OS" = "windows" ]; then
        BINARY_NAME="${BINARY_NAME}.exe"
    fi
    
    DOWNLOAD_URL="${DOWNLOAD_BASE}/${VERSION}/${BINARY_NAME}"
    
    log "Downloading from: $DOWNLOAD_URL"
    
    # Create temp directory
    TMPDIR=$(mktemp -d)
    cd "$TMPDIR"
    
    # Download with retry
    for i in 1 2 3; do
        if curl -fsSL "$DOWNLOAD_URL" -o "$BINARY_NAME"; then
            break
        fi
        warn "Download attempt $i failed, retrying..."
        sleep 2
    done
    
    # Verify the download
    if [ ! -f "$BINARY_NAME" ]; then
        error "Download failed"
        return 1
    fi
    
    # Run cosign verification if available
    verify_cosign || true
    
    # Create installation directory
    mkdir -p "$(dirname "$INSTALL_PATH")"
    
    # Move binary to installation path
    mv "$BINARY_NAME" "$INSTALL_PATH"
    chmod +x "$INSTALL_PATH"
    
    # Cleanup
    cd /
    rm -rf "$TMPDIR"
    
    log "Installation complete!"
    return 0
}

# Create log directory
setup_logging() {
    mkdir -p "$LOG_PATH"
    log "Logs will be written to: $LOG_PATH"
}

# Main installation
main() {
    log "Starting ODIN AI installation..."
    log "Version: $VERSION"
    log "Target path: $INSTALL_PATH"
    
    # Setup logging first
    setup_logging
    
    # Detect environment
    OS=$(detect_os)
    ARCH=$(detect_arch)
    CONTAINER=$(detect_container)
    
    log "Detected OS: $OS, Arch: $ARCH, Container: ${CONTAINER:-none}"
    
    # Check for existing installation
    backup_existing
    
    # Download and install
    if ! download_and_install; then
        error "Installation failed!"
        
        # Run rollback on failure if available
        if [ -f "$BACKUP_PATH/rollback.sh" ]; then
            warn "Running automatic rollback..."
            bash "$BACKUP_PATH/rollback.sh"
        fi
        
        exit 1
    fi
    
    # Verify installation
    if [ -f "$INSTALL_PATH" ]; then
        log "Verifying installation..."
        "$INSTALL_PATH" version
    fi
    
    log "ODIN AI installed successfully!"
    log "Run 'odin --help' to get started"
}

main "$@"
`

	// Determine cosign key from config or use empty string
	cosignKey := ""
	if cfg != nil && cfg.CosignKey != "" {
		cosignKey = cfg.CosignKey
	}

	data := struct {
		InstallPath string
		BackupPath  string
		LogPath     string
		CosignKey   string
		Version     string
		DownloadURL string
	}{
		InstallPath: info.InstallPath,
		BackupPath:  cfg.BackupPath,
		LogPath:     cfg.LogPath,
		CosignKey:   cosignKey,
		Version:     "1.0.0",
		DownloadURL: "https://get.odin.ai/releases",
	}

	t, err := template.New("install.sh").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// WriteInstallScript writes the installation script to a file
func WriteInstallScript(path string, info *SystemInfo, cfg *DeployConfig) error {
	script, err := GenerateInstallScript(info, cfg)
	if err != nil {
		return err
	}

	if err := os.WriteFile(path, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write install script: %w", err)
	}

	return nil
}

// InstallScriptPath returns the default path for the install script
func InstallScriptPath() string {
	homeDir, _ := os.UserHomeDir()
	return filepath.Join(homeDir, ".odin", "install.sh")
}
